### ISSUE TITLE
Milestone 2 Deliverables

### ISSUE THREAD

**Issue by ruben1dlg** [UBC-MDS/magmaviz#14]
Python package:
- [x] Code for corr plot
- [x] Code for box plot
- [x] Code for histogram
- [x] Code for scatter plot
- [x] Test script for corr plot
- [x] Test script for box plot
- [x] Test script for histogram
- [x] Test script for scatter plot
